include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    always_declare_return_types: true
    avoid_annotating_with_dynamic: true
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: true
    avoid_empty_else: true
    avoid_multiple_declarations_per_line: true
    avoid_private_typedef_functions: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_void_async: true
    avoid_web_libraries_in_flutter: false
    camel_case_extensions: true
    cancel_subscriptions: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    comment_references: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    enable_null_safety: true
    hash_and_equals: true
    invalid_case_patterns: true
    leading_newlines_in_multiline_strings: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_duplicate_case_values: true
    no_leading_underscores_for_local_identifiers: true
    only_throw_errors: true
    prefer_const_constructors_in_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_single_quotes: true
    require_trailing_commas: true
    secure_pubspec_urls: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_build_context_synchronously: false
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_string_buffers: true
    valid_regexps: true
# https://dart.dev/guides/language/analysis-options
